[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"

[nl]
  languageName = "Nederlands"
  contentDir = "content/nl"
  weight = 20